### ISSUE TITLE
Problems running on Ubuntu 14.04

### ISSUE THREAD

**Issue by psicus78** [CoreCompat/CoreCompat#1]
Hello,
I was trying to use you library on linux, more precisely I was trying to use BitmapImage class.
However I get an exception while initializing the image object:

```
System.TypeInitializationException : The type initializer for 'System.Drawing.GDIPlus' threw an exception.
      ---- System.DllNotFoundException : Unable to load DLL 'gdiplus.dll': The specified module could not be found.
       (Exception from HRESULT: 0x8007007E)
      Stack Trace:
           at System.Drawing.GDIPlus.GdipCreateBitmapFromFile(String filename, IntPtr& bitmap)
           at System.Drawing.Bitmap..ctor(String filename, Boolean useIcm)
           at System.Drawing.Bitmap..ctor(String filename)
           at LCR.UnitTests.DummyTest.TestDummyService(Int32 value)
        ----- Inner Stack Trace -----
           at System.Drawing.GDIPlus.GdiplusStartup(UInt64& token, GdiplusStartupInput& input, GdiplusStartupOutput& output)
           at System.Drawing.GDIPlus..cctor()
```

We thought that the problem was with libgdi, however it looks like it's installed:

```
ldconfig -p |grep libgdiplus
libgdiplus.so.0 (libc6,x86-64) => /usr/lib/libgdiplus.so.0
libgdiplus.so (libc6,x86-64) => /usr/lib/libgdiplus.so
```

Could you please help me investigating the problem?

thanks.

**Comment by qmfrederik** [comment]
Hi @psicus78 ,

Thanks for trying the library & creating an issue here!

It looks like the issue is because of the name of the gdiplist library -- [the P/Invoke definition for `GdipCreateBitmapFromFile`](https://github.com/qmfrederik/mono/blob/coreclr/system.drawing/mcs/class/System.Drawing/System.Drawing/gdipFunctions.cs#L1173) uses `gdiplus.dll` as a name, whereas I believe it should just be `gdiplus` (without the `.dll` at the end). I've seen this cause cross-platform issues in other projects I've done.

You seem to be a bit ahead of me (haven't done extensive testing on Linux yet). I'll definitely look into this but it may take some time.

If you want to go ahead & investigate yourself, here are some pointers as to how you can compile from source:

* Check out the `coreclr/system.drawing` branch of my fork of the Mono repository:
```
git clone https://github.com/qmfrederik/mono/
cd mono
git checkout coreclr/system.drawing
```

* Check out the CoreCompat repository:
```
git clone https://github.com/CoreCompat/CoreCompat/
cd CoreCompat/src/CoreCompat.System.Drawing
```

You will need to modify the paths in the `project.json` file so that they reference your local copy of the Mono repository.

Then, you can make the package as usual:
```
dotnet restore
dotnet build
```

The plan is to get the build and associated tests working on AppVeyor/Travis but it may take some time :-)

**Comment by psicus78** [comment]
Hi @qmfrederik ,
thanks for your reply.
I eventually found some time to try your solution and it works.
Replacing DllImport("gdiplus.dll") with DllImport("gdiplus") seems to work both in windows and ubuntu 14.04!!

It would be great if you could release a working version, however I can work with a local version of your library for now.

Thank you again for your help.

**Comment by qmfrederik** [comment]
Hi @psicus78 ,

Sounds great, thanks! If you can, feel free to send me a PR for the changes, if not, can you let me know if the `[DllImport("gdiplus.dll")]` to `[DllImport("gdiplus")]` was the only change you had to make?

I hope to update the NuGet package next week, but no hard promises though.

**Comment by qmfrederik** [comment]
I've updated the NuGet package (`1.0.0-beta005` has your fixes and now targets `netstandard1.3` instead of `netstandard1.5`).

Let me know if it works for you!

**Comment by psicus78** [comment]
Works perfectly! 
Thanks!
