### ISSUE TITLE
Library names Conflict 

### ISSUE THREAD

**Issue by VitoHanoi** [CoreCompat/CoreCompat#12]
Hi everyone,
I have a conflict with System.Drawing .NETStandard2.0 ! 
I got this error :

Error	CS0433	The type 'Bitmap' exists in both 'CoreCompat.System.Drawing, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' and 'System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"

Beginners as I am, i didn't manage to solve it even with adding alias name because nugget package doesn't have the Alias properties. Any ideas? 

Thanks a lot,
Vito

**Comment by qmfrederik** [comment]
Hi @VitoHanoi 

For .NET Standard 2.0 and .NET Core 2.0, I've prepared a new package (because of the API surface changes). Can you have a look at https://www.nuget.org/packages/CoreCompat.System.Drawing.v2 and let me know whether it works for you?

NOTE: For this version, we no longer ship libgdiplus with the NuGet package, so you'll need to make sure you've installed libgdiplus via your Linux distribution.

Let me know how it goes!

**Comment by VitoHanoi** [comment]
Hi @qmfrederik 

Thank you for answer me but I was already using this prerelease. The problem is that to use it i have to write:
using System.Drawing (which already exists in .NetFramework4.6.1 and .NetStandard 2.0). So i was wandering how can you make it work when you are using these dependencies in your poject.

I thought I could use like : CoreCompat.System.Drawing but unfortunately, cant do that.
Do you have a solution either NOT include the classic System.Drawing or just to difference yours. Cant you rename the namespace as CoreCompat.System.Drawing?

Im running on Windows. Do I have to install something else? 
Cheers

**Comment by qmfrederik** [comment]
Hi @VitoHanoi 

Can you please double check you are using `CoreCompat.System.Drawing.v2` and not `CoreCompat.System.Drawing` - note the v2 at the end?

The `.v2` package only includes the parts of `System.Drawing` which are not included in `netstandard2.0`,  so this should work just fine.

`System.Drawing.Bitmap` is not part of `netstandard2.0`, and it looks like you're having a conflict on `net4x`.

On `net4x` you cannot reference both `CoreCompat.System.Drawing.v2` and `System.Drawing` at the same time because they provide the same functionality. You can either:
- Remove the reference to `System.Drawing`
- Add the reference to `CoreCompat.System.Drawing.v2` for `netstandard2.0` only. You can do that like this in your `.csproj` file:
```
<ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0'">
    <PackageReference Include="CoreCompat.System.Drawing.v2" Version="5.2.0-preview1-r131" />
</ItemGroup>
```

Hope it helps!

**Comment by VitoHanoi** [comment]
Hi,

Thank you, It helps, it helps. So, I added the reference on netstandard2.0 and netcore2.0. Now it is working !!! I think it was a conflict inside .NetFramework4.6.1

Yes  Im using the v2 as you can see here:
![core](https://cloud.githubusercontent.com/assets/16385289/26605346/b97165be-45e1-11e7-8e4b-46e1c725925a.png)

But How can i remove the reference to System.Drawing? If i rightclick there is no option remove...

![net](https://cloud.githubusercontent.com/assets/16385289/26605523/84811ce0-45e2-11e7-874d-8d9654e66c65.png)
 
There is still one problem, Is it normal that I dont have some of  Bitmap functions like Save(stream, Image format)? Or some other function in Image codecinfo like:

![encoder](https://cloud.githubusercontent.com/assets/16385289/26606156/f4616022-45e4-11e7-85aa-df2f958514ae.png)

Thanks a lot

**Comment by VitoHanoi** [comment]
Yep, I had to restart Visual Studio and All good now :) Thank you again
