### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Ruslan-B** [CoreCompat/CoreCompat#17]
Hello,

Could you please specify license.

Cheers,
Ruslan

**Comment by qmfrederik** [comment]
Thanks, I added a license file. Because this project is based off Mono's version of System.Drawing, I use the same license - MIT X11.

That said, if you're going to target .NET Core 2.0, please use [System.Drawing.Common](System.Drawing.Common/4.5.0-preview1-25718-03) instead - it will be the official System.Drawing for .NET Core.

**Comment by Ruslan-B** [comment]
Thank a lot!
